## Numpy

In [1]:
import numpy as np

In [2]:
a = np.array((1, 2, 3, 4))

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [6]:
a.dtype

dtype('int64')

In [7]:
a = np.array([1,2,3])

In [8]:
a.dtype  # 数据类型

dtype('int64')

In [9]:
a.ndim  # 维度

1

In [17]:
b = np.array([[range(10), range(10), range(10)]])
b

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [18]:
b.ndim

3

In [21]:
a = np.array([[1,2,3], (1,2,3)])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
a.ndim

2

In [22]:
a = np.array([[1,2,3], (1,2)])
a

array([list([1, 2, 3]), (1, 2)], dtype=object)

In [23]:
a = np.array([range(10), range(3)])
a

array([range(0, 10), range(0, 3)], dtype=object)

In [24]:
a = np.array([list('abcd'), list('1234')])
a

array([['a', 'b', 'c', 'd'],
       ['1', '2', '3', '4']], dtype='<U1')

###  访问某个元素

In [27]:
a = np.array(range(25))

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
a[0]

0

In [30]:
a[-1]

24

In [31]:
a[-1] = -1

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, -1])

### 切片操作

In [33]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, -1])

In [34]:
a[1:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [35]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, -1])

### 修改 批量修改

In [36]:
a[:-5] = -1

In [37]:
a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, 20, 21, 22, 23, -1])

### MxN ndarray 访问

In [38]:
b = a.reshape(5,5)

In [39]:
b

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [20, 21, 22, 23, -1]])

In [41]:
b[0][0]

-1

In [43]:
b[4,0]

20

In [44]:
b[0]

array([-1, -1, -1, -1, -1])

### 取行 取列

In [45]:
b[1]  # 获取行

array([-1, -1, -1, -1, -1])

In [46]:
b[:,0]  # 获取列

array([-1, -1, -1, -1, 20])

###  指定某行，某列

In [47]:
b[[3,4]]

array([[-1, -1, -1, -1, -1],
       [20, 21, 22, 23, -1]])

In [48]:
b[:,[1,2]]

array([[-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [21, 22]])

In [50]:
b[::2]

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [20, 21, 22, 23, -1]])

### 取指定行列

In [51]:
b[:, :2]

array([[-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [20, 21]])

In [52]:
b[1:-1, 1:-1]

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [53]:
b[1:-1, 1:-1] = 0
b

array([[-1, -1, -1, -1, -1],
       [-1,  0,  0,  0, -1],
       [-1,  0,  0,  0, -1],
       [-1,  0,  0,  0, -1],
       [20, 21, 22, 23, -1]])

### zeros/ones/empty/full

In [3]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled wi

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array se

In [9]:
np.full(10, -1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

### zeros_like/ones_like/empty_like/full_like

In [10]:
help(np.zeros_like)

Help on function zeros_like in module numpy.core.numeric:

zeros_like(a, dtype=None, order='K', subok=True)
    Return an array of zeros with the same shape and type as a given array.
    
    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    
        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    
        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.
    
    Returns
    -------
    out : ndarray
  

In [11]:
np.zeros_like([1,2,3,4])

array([0, 0, 0, 0])

In [12]:
np.ones_like([1,2,3,4])

array([1, 1, 1, 1])

In [13]:
np.empty_like([1,2,3,4])

array([ 2305843009213693952, -3458755719616715390, -3458755719618887678,
            571744157244314])

In [14]:
help(np.full_like)

Help on function full_like in module numpy.core.numeric:

full_like(a, fill_value, dtype=None, order='K', subok=True)
    Return a full array with the same shape and type as a given array.
    
    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        Overrides the data type of the result.
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.
    
    Returns
    -------
    out : ndarray
        Array of `fill_valu

In [15]:
np.full_like([1,2,3,4], -1)

array([-1, -1, -1, -1])

### arange/linspace

In [16]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [20]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0, 10, 11, endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

### random

In [24]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    ==================== =========================================================
    Utility functions
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    rand                 Uniformly distributed values.
    randn

In [25]:
np.random.rand(10)

array([0.44902808, 0.66583347, 0.83298792, 0.66489623, 0.35222034,
       0.56110565, 0.56135026, 0.66999807, 0.01533793, 0.70302022])

In [26]:
np.random.rand(10, 2)

array([[0.61450308, 0.25355853],
       [0.64219476, 0.69285735],
       [0.08289681, 0.69918892],
       [0.25183037, 0.9621561 ],
       [0.7040974 , 0.54946263],
       [0.05197441, 0.85180448],
       [0.95762179, 0.74336184],
       [0.51694954, 0.89785531],
       [0.91210839, 0.41190796],
       [0.66457369, 0.62973662]])

In [27]:
np.random.rand(10, 2, 3)

array([[[0.83454973, 0.69925572, 0.4177491 ],
        [0.87129089, 0.32093465, 0.1535406 ]],

       [[0.74100377, 0.40860684, 0.44771735],
        [0.62142784, 0.59305271, 0.51580388]],

       [[0.20137071, 0.45941049, 0.4857113 ],
        [0.68467334, 0.56891586, 0.49157227]],

       [[0.6307615 , 0.91133827, 0.45896691],
        [0.81370324, 0.79353783, 0.86145059]],

       [[0.49911476, 0.96055909, 0.49960383],
        [0.7432686 , 0.20935838, 0.57190324]],

       [[0.33179542, 0.79989096, 0.48098585],
        [0.21723338, 0.71805624, 0.81530243]],

       [[0.49977904, 0.51625652, 0.65316251],
        [0.68017342, 0.16038077, 0.71738724]],

       [[0.77320706, 0.7684269 , 0.51478973],
        [0.09070362, 0.49420233, 0.38016349]],

       [[0.28353187, 0.15905249, 0.30958726],
        [0.69844251, 0.43860564, 0.98022764]],

       [[0.08589777, 0.69484017, 0.05669574],
        [0.04546283, 0.80020455, 0.80213327]]])

In [29]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [30]:
np.random.randn(10)

array([-1.09511984, -0.57556858,  0.64989519, -0.50606196, -0.67403218,
       -0.45077669, -0.85841639, -0.58348376, -1.43504883, -0.30823864])

In [31]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [32]:
np.random.randint(0, 10, 10)

array([4, 0, 9, 3, 8, 3, 5, 3, 0, 4])

In [34]:
np.random.randint(0, 10, (2, 2, 3))

array([[[2, 7, 1],
        [0, 1, 2]],

       [[9, 1, 1],
        [2, 3, 7]]])

### eye/identity/diagflat

In [35]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [38]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
np.diag(np.arange(10))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [41]:
d = np.diag(np.arange(10))

In [42]:
np.diag(d)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.diagflat(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [44]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 数据类型

In [45]:
np.array(3, dtype=np.bool)

array(True)

In [47]:
np.array(np.arange(10), dtype=np.bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
np.full(5, 10, dtype=np.float64)

array([10., 10., 10., 10., 10.])

In [51]:
np.array(np.random.randn(5), dtype=np.int64)

array([ 0, -1,  0,  0,  0])

In [52]:
np.array(np.random.randn(5), dtype='i4')

array([ 0,  0,  0, -1,  0], dtype=int32)

In [53]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(obj, align=False, copy=False)
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  obj
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  
 |  See also
 |  --------
 |  result_type
 |  
 |  Examples
 |  --------
 |  Usin

In [55]:
np.array(np.arange(10), dtype='?')

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
np.array(np.arange(10), dtype='f')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [57]:
np.array(np.arange(10), dtype='S1')

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S1')

In [58]:
np.typeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.int64,
 'q': numpy.int64,
 9: numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 10: numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,


In [59]:
np.typecodes

{'Character': 'c',
 'Integer': 'bhilqp',
 'UnsignedInteger': 'BHILQP',
 'Float': 'efdg',
 'Complex': 'FDG',
 'AllInteger': 'bBhHiIlLqQpP',
 'AllFloat': 'efdgFDG',
 'Datetime': 'Mm',
 'All': '?bhilqpBHILQPefdgFDGSUVOMm'}

In [60]:
np.typeNA

{'Bool': numpy.bool_,
 numpy.bool_: 'Bool',
 '?': 'Bool',
 'b1': 'Bool',
 'Float16': numpy.float16,
 numpy.float16: 'Float16',
 'e': 'Float16',
 'f2': 'Float16',
 'Float32': numpy.float32,
 numpy.float32: 'Float32',
 'f': 'Float32',
 'f4': 'Float32',
 'Float64': numpy.float64,
 numpy.float64: 'Float64',
 'd': 'Float64',
 'f8': 'Float64',
 'Float128': numpy.float128,
 numpy.float128: 'Float128',
 'g': 'Float128',
 'f16': 'Float128',
 'Complex32': numpy.complex64,
 numpy.complex64: 'Complex32',
 'F': 'Complex32',
 'c8': 'Complex32',
 'Complex64': numpy.complex128,
 numpy.complex128: 'Complex64',
 'D': 'Complex64',
 'c16': 'Complex64',
 'Complex128': numpy.complex256,
 numpy.complex256: 'Complex128',
 'G': 'Complex128',
 'c32': 'Complex128',
 'Object0': numpy.object_,
 numpy.object_: 'Object0',
 'O': 'Object0',
 'Bytes0': numpy.bytes_,
 numpy.bytes_: 'Bytes0',
 'S': 'Bytes0',
 'Str0': numpy.str_,
 numpy.str_: 'Str0',
 'U': 'Str0',
 'Void0': numpy.void,
 numpy.void: 'Void0',
 'V': 'Void0',

### 数据 : name, age 例如: (['sun', 10], ['yang', 10]), 转换成array

In [62]:
np.array([('sun', 10), ('yang', 11)])

array([['sun', '10'],
       ['yang', '11']], dtype='<U4')

In [63]:
np.dtype(np.int16)

dtype('int16')

In [65]:
np.zeros(10, dtype=np.dtype(np.unicode))

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [68]:
dt = np.dtype('U16, i4')

In [69]:
dt

dtype([('f0', '<U16'), ('f1', '<i4')])

###  自定义数据类型

In [70]:
np.array([('sun', 10), ('yang', 11)], dtype=dt)

array([('sun', 10), ('yang', 11)], dtype=[('f0', '<U16'), ('f1', '<i4')])

In [71]:
a = np.array([('sun', 10), ('yang', 11)], dtype=dt)

In [72]:
a[0]

('sun', 10)

In [73]:
a[0][0]

'sun'

In [74]:
a['f0']

array(['sun', 'yang'], dtype='<U16')

In [75]:
np.zeros(10, dtype=dt)

array([('', 0), ('', 0), ('', 0), ('', 0), ('', 0), ('', 0), ('', 0),
       ('', 0), ('', 0), ('', 0)], dtype=[('f0', '<U16'), ('f1', '<i4')])

In [76]:
np.ones(10, dtype=dt)

array([('1', 1), ('1', 1), ('1', 1), ('1', 1), ('1', 1), ('1', 1),
       ('1', 1), ('1', 1), ('1', 1), ('1', 1)],
      dtype=[('f0', '<U16'), ('f1', '<i4')])

In [77]:
dt = np.dtype('S10, 3S8')

In [78]:
np.zeros(4, dtype=dt)

array([(b'', [b'', b'', b'']), (b'', [b'', b'', b'']),
       (b'', [b'', b'', b'']), (b'', [b'', b'', b''])],
      dtype=[('f0', 'S10'), ('f1', 'S8', (3,))])

In [79]:
dt = np.dtype('S10, 3S8, (3,4)i4')

In [81]:
a = np.ones(4, dtype=dt)

In [82]:
a['f0']

array([b'1', b'1', b'1', b'1'], dtype='|S10')

In [83]:
a['f1']

array([[b'1', b'1', b'1'],
       [b'1', b'1', b'1'],
       [b'1', b'1', b'1'],
       [b'1', b'1', b'1']], dtype='|S8')

In [85]:
a['f2'][:, -1]

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [86]:
dt = np.dtype([('name','U16'), ('age','i4')])

In [87]:
dt

dtype([('name', '<U16'), ('age', '<i4')])

In [88]:
a = np.array([('sun', 10), ('li', 11)], dtype=dt)

In [89]:
a

array([('sun', 10), ('li', 11)], dtype=[('name', '<U16'), ('age', '<i4')])

In [90]:
dt = np.dtype([('f0', [('name', 'U16'), ('age', 'i4')])])

In [91]:
dt

dtype([('f0', [('name', '<U16'), ('age', '<i4')])])

In [92]:
a = np.ones(4, dtype=dt)

In [93]:
a

array([(('1', 1),), (('1', 1),), (('1', 1),), (('1', 1),)],
      dtype=[('f0', [('name', '<U16'), ('age', '<i4')])])

In [94]:
a['f0']

array([('1', 1), ('1', 1), ('1', 1), ('1', 1)],
      dtype=[('name', '<U16'), ('age', '<i4')])

In [95]:
a['f0']['name']

array(['1', '1', '1', '1'], dtype='<U16')

In [97]:
a = np.array([(('sun', 10),)], dtype=dt)

In [98]:
a['f0']['age']

array([10], dtype=int32)

In [99]:
dt = np.dtype([('f0', [('name', 'U16'), ('score', 'i4', 3)])])

In [100]:
np.ones(2, dtype=dt)

array([(('1', [1, 1, 1]),), (('1', [1, 1, 1]),)],
      dtype=[('f0', [('name', '<U16'), ('score', '<i4', (3,))])])

In [101]:
dt = np.dtype([('f0', [('name', 'U16'), ('score', 'i4', (3,3))])])

In [102]:
np.ones(2, dtype=dt)

array([(('1', [[1, 1, 1], [1, 1, 1], [1, 1, 1]]),),
       (('1', [[1, 1, 1], [1, 1, 1], [1, 1, 1]]),)],
      dtype=[('f0', [('name', '<U16'), ('score', '<i4', (3, 3))])])

In [103]:
dt = np.dtype({'x': ('S2', 0), 'y': ('i4', 2)})

In [104]:
dt

dtype([('x', 'S2'), ('y', '<i4')])

In [106]:
dt2 = np.dtype({'x': ('S2', 0), 'y': ('i4', 1)})

In [107]:
np.array(('1', 222), dtype=dt)

array((b'1', 222), dtype=[('x', 'S2'), ('y', '<i4')])

In [108]:
np.array(('1', 222), dtype=dt2)

array((b'1\xde', 222),
      dtype={'names':['x','y'], 'formats':['S2','<i4'], 'offsets':[0,1], 'itemsize':5})

In [110]:
dt = np.dtype({'names':['name', 'age'], 'formats':['U16', 'i4']})
dt

dtype([('name', '<U16'), ('age', '<i4')])

In [116]:
a = np.array([('sun', 16), ('li', 15)], dtype = dt)

In [117]:
a

array([('sun', 16), ('li', 15)], dtype=[('name', '<U16'), ('age', '<i4')])

In [118]:
a['name']

array(['sun', 'li'], dtype='<U16')

###  Numpy 基本运算

In [121]:
a = np.arange(3)

In [122]:
a

array([0, 1, 2])

In [123]:
a + 2

array([2, 3, 4])

In [124]:
a * 2

array([0, 2, 4])

In [125]:
a-1

array([-1,  0,  1])

In [126]:
a+a

array([0, 2, 4])

In [128]:
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [130]:
a.shape

(3,)

In [131]:
b.shape

(3, 3)

### array之间运算

In [132]:
c = a.reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [135]:
a.shape, c.shape

((3,), (3, 1))

In [136]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 比较运算符

In [138]:
a = np.random.randint(10, size=(2,3))
a

array([[1, 8, 3],
       [0, 6, 4]])

In [139]:
a>5

array([[False,  True, False],
       [False,  True, False]])

In [140]:
indexs = [0,1]

In [142]:
a[indexs, 1]

array([8, 6])

In [143]:
a[[0, 1], 1]

array([8, 6])

In [144]:
bindexs = a>5

In [145]:
a[bindexs]

array([8, 6])

### Numpy 判断

In [146]:
a

array([[1, 8, 3],
       [0, 6, 4]])

In [147]:
b = a >5
b

array([[False,  True, False],
       [False,  True, False]])

In [148]:
np.all(b)

False

In [149]:
np.any(b)

True

In [150]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are

In [151]:
np.where(a>5, 1, -1)

array([[-1,  1, -1],
       [-1,  1, -1]])

In [152]:
np.where(a>5)

(array([0, 1]), array([1, 1]))

In [154]:
indexs = np.where(a > 5)
indexs

(array([0, 1]), array([1, 1]))

In [155]:
a[indexs]

array([8, 6])

In [156]:
a

array([[1, 8, 3],
       [0, 6, 4]])

In [160]:
np.where(((a>3) & (a<7)), True, False)

array([[False, False, False],
       [False,  True,  True]])

In [161]:
a

array([[1, 8, 3],
       [0, 6, 4]])

In [163]:
indexs = np.where(((a>3) & (a<7)))

In [164]:
a[indexs]

array([6, 4])

In [165]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [166]:
help(np.indices)

Help on function indices in module numpy.core.numeric:

indices(dimensions, dtype=<class 'int'>)
    Return an array representing the indices of a grid.
    
    Compute an array where the subarrays contain index values 0,1,...
    varying only along the corresponding axis.
    
    Parameters
    ----------
    dimensions : sequence of ints
        The shape of the grid.
    dtype : dtype, optional
        Data type of the result.
    
    Returns
    -------
    grid : ndarray
        The array of grid indices,
        ``grid.shape = (len(dimensions),) + tuple(dimensions)``.
    
    See Also
    --------
    mgrid, meshgrid
    
    Notes
    -----
    The output shape is obtained by prepending the number of dimensions
    in front of the tuple of dimensions, i.e. if `dimensions` is a tuple
    ``(r0, ..., rN-1)`` of length ``N``, the output shape is
    ``(N,r0,...,rN-1)``.
    
    The subarrays ``grid[k]`` contains the N-D array of indices along the
    ``k-th`` axis. Explicitly:

In [167]:
np.indices(a.shape)

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [168]:
r, c = np.indices(a.shape)
r,c

(array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]), array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]))

In [169]:
r==c

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [170]:
a[r==c] = 1

In [171]:
a

array([[1, 1, 2],
       [3, 1, 5],
       [6, 7, 1]])

In [172]:
a[r!=c] = 0
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [174]:
a = np.zeros((4,4), dtype='i4')
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [175]:
x, y = np.indices(a.shape)
x, y

(array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]), array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]))

In [176]:
a[(x+1) == y] = 1
a

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]], dtype=int32)

In [177]:
a[x == (y+1)] = 1
a

array([[0, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0]], dtype=int32)

### 常用统计方法

In [179]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [180]:
a = np.arange(9).reshape(3,3)

In [181]:
b = np.arange(3)

In [182]:
a, b

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([0, 1, 2]))

In [183]:
np.add(a, b)

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [184]:
np.info(np.prod)

 prod(a, axis=None, dtype=None, out=None, keepdims=<no value>,
      initial=<no value>)

Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `a` is signed then the
    platform integer is used while if `a` is

In [185]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [186]:
np.prod(a)

0

In [187]:
a[0,0]=1
a

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [188]:
np.prod(a)

40320

In [189]:
np.cumprod(a)

array([    1,     1,     2,     6,    24,   120,   720,  5040, 40320])

In [190]:
np.sum(a)

37

In [191]:
np.cumsum(a)

array([ 1,  2,  4,  7, 11, 16, 22, 29, 37])

In [192]:
scores = np.array([np.nan, 90, 80, 50, 60])
scores

array([nan, 90., 80., 50., 60.])

In [194]:
np.sum(scores)

nan

In [195]:
np.nansum(scores)

280.0

In [196]:
a

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [197]:
np.max(a)

8

In [198]:
np.min(a)

1

In [199]:
np.mean(a)

4.111111111111111

In [200]:
np.std(a)

2.4241582476968255

In [201]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same pr

In [202]:
a = np.random.randint(0,3, size=10)

In [203]:
b = np.random.randint(0,3, size=(3,3))
c = np.random.randint(0,3, size=(3,3,3))
d = np.random.randint(0,3, size=(3,3,3,3))

In [204]:
a

array([1, 0, 2, 0, 2, 2, 1, 1, 0, 0])

In [205]:
b

array([[2, 1, 1],
       [1, 0, 1],
       [1, 1, 2]])

In [206]:
c

array([[[2, 1, 1],
        [0, 0, 1],
        [1, 1, 2]],

       [[0, 2, 0],
        [1, 2, 0],
        [0, 2, 0]],

       [[0, 2, 1],
        [2, 1, 1],
        [2, 1, 1]]])

In [207]:
d

array([[[[0, 2, 2],
         [1, 1, 0],
         [1, 1, 0]],

        [[1, 2, 1],
         [2, 1, 0],
         [0, 0, 2]],

        [[2, 0, 0],
         [0, 1, 1],
         [2, 0, 2]]],


       [[[2, 2, 2],
         [2, 0, 1],
         [1, 2, 1]],

        [[2, 2, 0],
         [0, 2, 0],
         [2, 1, 1]],

        [[1, 0, 0],
         [0, 2, 1],
         [0, 2, 2]]],


       [[[1, 0, 0],
         [1, 1, 0],
         [0, 2, 0]],

        [[2, 0, 2],
         [2, 0, 2],
         [1, 1, 1]],

        [[2, 1, 0],
         [2, 0, 2],
         [0, 2, 2]]]])

In [208]:
np.sum(a)

9

In [209]:
np.sum(b)

10

In [210]:
np.sum(b, axis=0)

array([4, 2, 4])

In [211]:
np.sum(b, axis=1)

array([4, 2, 4])

In [212]:
c

array([[[2, 1, 1],
        [0, 0, 1],
        [1, 1, 2]],

       [[0, 2, 0],
        [1, 2, 0],
        [0, 2, 0]],

       [[0, 2, 1],
        [2, 1, 1],
        [2, 1, 1]]])

In [213]:
c.ndim

3

In [214]:
np.sum(c, axis=0)

array([[2, 5, 2],
       [3, 3, 2],
       [3, 4, 3]])

In [215]:
np.sum(c, axis=1)

array([[3, 2, 4],
       [1, 6, 0],
       [4, 4, 3]])

In [216]:
np.sum(c, axis=2)

array([[4, 1, 4],
       [2, 3, 2],
       [3, 4, 4]])